import assert from 'node:assert/strict';
import { readFile, readdir } from 'node:fs/promises';
import { DatabaseSync } from 'node:sqlite';
import vm from 'node:vm';
import { createHash, randomUUID } from 'node:crypto';
const html=await readFile('public/index.html','utf8');
const appScript=html.match(/<script id="app-script">([\s\S]*?)<\/script>/)[1];
new vm.Script(appScript);
assert(!html.includes('id="staff-select"'), 'There must be no staff impersonation picker');
const manifest=JSON.parse(await readFile('dist/.openai/hosting.json','utf8'));
assert(manifest.project_id && manifest.d1==='DB');
const source=await readFile('dist/server/index.js','utf8');
const {default:worker}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
assert.equal(typeof worker.fetch,'function');
const sqlite=new DatabaseSync(':memory:');
sqlite.exec('PRAGMA foreign_keys = ON');
for(const name of (await readdir('drizzle')).filter(name=>name.endsWith('.sql')).sort()) sqlite.exec(await readFile('drizzle/'+name,'utf8'));
sqlite.exec('PRAGMA optimize');
const binding={
  async batch(statements){sqlite.exec('BEGIN');try{const results=[];for(const statement of statements)results.push(await statement.run());sqlite.exec('COMMIT');return results;}catch(error){sqlite.exec('ROLLBACK');throw error;}},
  prepare(sql){const statement=sqlite.prepare(sql);let values=[];return {
    bind(...args){values=args;return this;},
    async run(){const result=statement.run(...values);return {meta:{changes:Number(result.changes)}};},
    async all(){return {results:statement.all(...values)};},
    async first(){return statement.get(...values)??null;},
  };},
};
const request=(path,method='GET',body,token='',owner=false)=>new Request('https://example.test'+path,{method,headers:{Origin:'https://example.test','Content-Type':'application/json',...(token?{Cookie:token}:{}),...(owner?{'oai-authenticated-user-email':'manager@company.test'}:{})},...(body===undefined?{}:{body:JSON.stringify(body)})});
const send=req=>worker.fetch(req,{DB:binding,HANDWASH_ADMIN_EMAIL:'manager@company.test',HANDWASH_SETTINGS_KEY:'b'.repeat(64),HANDWASH_SITE_ORIGIN:'https://example.test',HANDWASH_ALLOWED_ORIGIN:'https://024masahiro.github.io',HANDWASH_FRONTEND_URL:'https://024masahiro.github.io/handwash-log'});
const parsed=async req=>{const response=await send(req);assert.equal(response.status,200);return response.json();};
const range='/api/records?from='+(Date.now()-86400000)+'&to='+(Date.now()+86400000);
const summary='/api/admin/summary?from='+(Date.now()-86400000)+'&to='+(Date.now()+86400000);
const page=await send(request('/'));assert.equal(page.status,200);assert(page.headers.get('Content-Security-Policy').includes(createHash('sha256').update(appScript).digest('base64')));
assert(!html.includes('<textarea'),'No comma-separated entry');assert(!html.includes('職員番号'));assert(!html.includes('roster-code'));
for(const name of ['register-name','register-email','register-password'])assert(html.includes('id="'+name+'"'));
assert.equal((await send(request(range))).status,401);
assert.equal((await parsed(request('/api/bootstrap'))).authenticated,false);
const people=[{name:'管理者',email:'manager@company.test',password:'manager-password',isAdmin:true},{name:'山田',email:'alpha@company.test',password:'alpha-password'},{name:'鈴木',email:'beta@company.test',password:'beta-password'}];
assert.equal((await send(request('/api/admin/owner-account','POST',{name:people[0].name,password:people[0].password},'',true))).status,200);
for(const person of people.slice(1))assert.equal((await send(request('/api/auth/register','POST',person))).status,201);
assert.equal((await send(request('/api/auth/register','POST',{name:'攻撃者',email:'hacker@company.test',password:'hacker-password',isAdmin:true}))).status,400);
assert.equal((await send(request('/api/admin/owner-account','POST',{name:'攻撃者',password:'hacker-password'}))).status,401);
assert.equal((await send(request('/api/auth/register','POST',people[1]))).status,409);
assert.equal((await send(request('/api/auth/register','POST',{...people[1],email:'third@company.test',password:'123'}))).status,400);
const login=async(email,password)=>{const r=await send(request('/api/auth/login','POST',{email,password}));assert.equal(r.status,200);const cookie=r.headers.get('Set-Cookie');assert(cookie.includes('HttpOnly')&&cookie.includes('Secure')&&cookie.includes('SameSite=Strict'));return cookie.split(';')[0];};
assert.equal((await send(request('/api/auth/login','POST',{email:'alpha@company.test',password:'wrong'}))).status,401);
const manager=await login('manager@company.test','manager-password'),a=await login('alpha@company.test','alpha-password'),b=await login('beta@company.test','beta-password');
const staffA=(await parsed(request('/api/bootstrap','GET',undefined,a))).myStaff.id,staffB=(await parsed(request('/api/bootstrap','GET',undefined,b))).myStaff.id;
assert.equal((await parsed(request('/api/bootstrap','GET',undefined,manager))).isAdmin,true);
assert(!Object.hasOwn(await parsed(request('/api/bootstrap','GET',undefined,a)),'staff'));
assert.equal((await send(request(summary,'GET',undefined,a))).status,403);
assert.equal((await send(request(range+'&staff='+staffB,'GET',undefined,a))).status,403);
assert.equal((await send(request('/api/records','POST',{id:randomUUID(),staffId:staffB},a))).status,400);
const idA=randomUUID(),idB=randomUUID();
assert.equal((await send(request('/api/records','POST',{id:idA},a))).status,201);
assert.equal((await send(request('/api/records','POST',{id:idA},a))).status,201);
assert.equal((await send(request('/api/records','POST',{id:idB},b))).status,201);
assert.equal((await parsed(request(range,'GET',undefined,a))).records.length,1);
assert.equal((await parsed(request(range,'GET',undefined,b))).records[0].id,idB);
assert.equal((await parsed(request(summary,'GET',undefined,manager))).total,2);
assert.equal((await send(request('/api/records/'+idB,'DELETE',undefined,a))).status,403);
assert.equal((await send(request('/api/records/'+idA,'DELETE',undefined,manager))).status,403);
assert.equal((await send(request('/api/records/'+idA,'DELETE',undefined,a))).status,200);
const cross=request('/api/auth/login','POST',{email:'alpha@company.test',password:'alpha-password'});cross.headers.set('Origin','https://evil.test');assert.equal((await send(cross)).status,403);
assert.equal((await send(request('/api/admin/staff/'+staffA+'/account','POST',{...people[1],password:'reset-password'},manager))).status,200);
assert.equal((await send(request(range,'GET',undefined,a))).status,401,'Admin reset revokes sessions');
assert.equal((await send(request('/api/auth/login','POST',{email:'alpha@company.test',password:'alpha-password'}))).status,401);
const reset=await login('alpha@company.test','reset-password');
assert.equal((await send(request('/api/auth/password','POST',{currentPassword:'bad',password:'new-password-123'},reset))).status,403);
assert.equal((await send(request('/api/auth/password','POST',{currentPassword:'reset-password',password:'new-password-123'},reset))).status,200);
assert.equal((await send(request(range,'GET',undefined,reset))).status,401);
const changed=await login('alpha@company.test','new-password-123');
assert.equal((await send(request('/api/auth/logout','POST',undefined,changed))).status,200);
assert.equal((await send(request(range,'GET',undefined,changed))).status,401);
const managerId=(await parsed(request('/api/bootstrap','GET',undefined,manager))).myStaff.id;
assert.equal((await send(request('/api/admin/staff/'+managerId+'/account','POST',{...people[0],isAdmin:false,password:''},manager))).status,403);
assert.equal((await send(request('/api/admin/owner-account','POST',{name:'管理者',password:'manager-password'},manager))).status,403);
assert.equal((await send(request('/api/admin/staff/'+staffB+'/account','POST',{...people[2],isAdmin:true},manager))).status,403);
const legacy=randomUUID();sqlite.prepare('INSERT INTO staff (id,name,code) VALUES (?,?,?)').run(legacy,'旧職員','old');
assert.equal((await send(request('/api/admin/staff/'+legacy+'/account','POST',{name:'旧職員',email:'legacy@company.test',password:'legacy-password'},manager))).status,200);
await login('legacy@company.test','legacy-password');
assert.equal((await send(request('/api/auth/forgot','POST',{email:people[1].email}))).status,503);
const originalFetch=globalThis.fetch,mail=[];globalThis.fetch=async(url,options)=>{assert.equal(url,'https://api.resend.com/emails');mail.push(JSON.parse(options.body));return new Response('{}',{status:200});};
assert.equal((await send(request('/api/admin/mail','POST',{from:'handwash@company.test',apiKey:'re_fake_key_for_testing'},manager))).status,403);
assert.equal((await send(request('/api/admin/mail','POST',{from:'handwash@company.test',apiKey:'re_fake_key_for_testing'},'',true))).status,200);
assert(!sqlite.prepare("SELECT value FROM app_settings WHERE key='mail'").get().value.includes('re_fake_key'));
assert.equal((await parsed(request('/api/admin/mail','GET',undefined,'',true))).from,'handwash@company.test');
assert.equal((await send(request('/api/auth/forgot','POST',{email:people[1].email}))).status,200);
assert.equal(mail.at(-1).to[0],people[1].email);assert(mail.at(-1).html.includes('https://024masahiro.github.io/handwash-log/reset/#token='));const resetToken=mail.at(-1).html.match(/#token=([a-f0-9]{64})/)[1];
assert(!sqlite.prepare('SELECT token_hash FROM password_resets').all().some(row=>row.token_hash===resetToken));
const beforeReset=await login(people[1].email,'new-password-123');
const [reset1,reset2]=await Promise.all([send(request('/api/auth/reset','POST',{token:resetToken,password:'email-reset-password'})),send(request('/api/auth/reset','POST',{token:resetToken,password:'email-reset-password'}))]);assert.deepEqual([reset1.status,reset2.status].sort(),[200,400]);
assert.equal((await send(request(range,'GET',undefined,beforeReset))).status,401);
const afterReset=await login(people[1].email,'email-reset-password');
assert.equal((await send(request('/api/auth/reset','POST',{token:resetToken,password:'another-password'}))).status,400);
assert.equal((await send(request('/api/auth/forgot','POST',{email:people[2].email}))).status,200);const expired=mail.at(-1).html.match(/#token=([a-f0-9]{64})/)[1];sqlite.prepare('UPDATE password_resets SET expires_at=0').run();assert.equal((await send(request('/api/auth/reset','POST',{token:expired,password:'expired-password'}))).status,400);
const unknown=await parsed(request('/api/auth/forgot','POST',{email:'unregistered@company.test'}));assert.equal(Object.keys(unknown).join(','),'message');
globalThis.fetch=originalFetch;
assert.equal((await send(request('/api/account','DELETE',{password:'bad'},afterReset))).status,403);
assert.equal((await send(request('/api/account','DELETE',{password:'email-reset-password'},afterReset))).status,200);
assert.equal((await send(request(range,'GET',undefined,afterReset))).status,401);assert.equal(sqlite.prepare('SELECT id FROM staff WHERE id=?').get(staffA),undefined);
assert.equal((await send(request('/api/admin/staff/'+staffB,'DELETE',undefined,b))).status,403);
assert.equal((await send(request('/api/admin/staff/'+staffB,'DELETE',undefined,manager))).status,200);assert.equal(sqlite.prepare('SELECT id FROM washes WHERE staff_id=?').get(staffB),undefined);
assert.equal((await send(request('/api/admin/staff/'+managerId,'DELETE',undefined,manager))).status,403);
for(let i=0;i<12;i++)await send(request('/api/auth/login','POST',{email:'missing@company.test',password:'wrong-password'}));
assert.equal((await send(request('/api/auth/login','POST',{email:'missing@company.test',password:'wrong-password'}))).status,429);
assert(!sqlite.prepare('SELECT password_hash FROM staff').all().some(row=>row.password_hash?.includes('manager-password')));
const pagesRequest=(path,method='GET',body,token='')=>new Request('https://example.test'+path,{method,headers:{Origin:'https://024masahiro.github.io','Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},...(body===undefined?{}:{body:JSON.stringify(body)})});
const preflight=pagesRequest('/api/auth/login','OPTIONS');preflight.headers.set('Access-Control-Request-Method','POST');preflight.headers.set('Access-Control-Request-Headers','authorization,content-type');assert.equal((await send(preflight)).status,204);
const badPreflight=pagesRequest('/api/auth/login','OPTIONS');badPreflight.headers.set('Access-Control-Request-Method','POST');badPreflight.headers.set('Access-Control-Request-Headers','oai-authenticated-user-email');assert.equal((await send(badPreflight)).status,403);
const pagesLogin=await send(pagesRequest('/api/auth/login','POST',{email:'legacy@company.test',password:'legacy-password'}));assert.equal(pagesLogin.status,200);assert.equal(pagesLogin.headers.get('Access-Control-Allow-Origin'),'https://024masahiro.github.io');assert.equal(pagesLogin.headers.get('Set-Cookie'),null);const bearer=(await pagesLogin.json()).token;assert(/^[a-f0-9]{64}$/.test(bearer));
assert.equal((await parsed(pagesRequest('/api/bootstrap','GET',undefined,bearer))).myStaff.id,legacy);
const cookieOnly=pagesRequest('/api/bootstrap');cookieOnly.headers.set('Cookie',manager);cookieOnly.headers.set('oai-authenticated-user-email','manager@company.test');assert.equal((await parsed(cookieOnly)).authenticated,false,'Pages must not use platform identity or backend cookies');
assert.equal((await send(pagesRequest(summary,'GET',undefined,bearer))).status,403);
const pageWash=randomUUID();assert.equal((await send(pagesRequest('/api/records','POST',{id:pageWash},bearer))).status,201);
assert.equal((await send(pagesRequest('/api/auth/logout','POST',undefined,bearer))).status,200);assert.equal((await send(pagesRequest(range,'GET',undefined,bearer))).status,401);
const rows=sqlite.prepare('SELECT token_hash FROM sessions').all();assert(rows.every(row=>row.token_hash.length===64));
sqlite.close();
console.log('Passed: self-registration, admin role injection refused, owner-only setup, private dashboard, withdrawal and deletion, encrypted email settings, reset mail, expired/single-use links, reset races, session revocation, record isolation and allowed-origin-only Pages bearer sessions.');
